### ISSUE TITLE
Feature Request: Remember the last window size

### ISSUE THREAD

**Issue by Gameranand** [rhyswilliamsza/GoogleKeepDesktop#1]
As of now after opening I have to resize the window after every restart as I have put this in startup. If possible kindly make it remember the last size and location of the window.

**Comment by rhyswilliamsza** [comment]
Hi @Gameranand,

I have updated the app to remember the window state. Please go ahead and download the new version as there is no auto-update feature

**Comment by rhyswilliamsza** [comment]
#
